[
  {
    name: "Nón bảo hiểm fullface Barock sợi carbon cao cấp B510 (đen mờ)",
    price: 4495,
    sale: 4495,
    img: "https://i.ibb.co/WvpptFp/2409202401.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 0,
    rating: 4.5,
    sale_count: 120,
  },
  {
    name: "Nón bảo hiểm 3/4 kính âm Nolan N21 Visor Classic – Nhập khẩu chính hãng",
    price: 4550,
    sale: 3950,
    img: "https://i.ibb.co/hX6CSv8/2409202402.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 13,
    rating: 4.7,
    sale_count: 230,
  },
  {
    name: "Mũ bảo hiểm vỏ sò đen bóng Rona",
    price: 250,
    sale: 150,
    img: "https://i.ibb.co/VNwHjs5/2409202403.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 40,
    rating: 4.3,
    sale_count: 85,
  },
  {
    name: "Mũ bảo hiểm vỏ sò trắng bóng Rona",
    price: 250,
    sale: 150,
    img: "https://i.ibb.co/QpRgZDJ/2409202404.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 40,
    rating: 4.2,
    sale_count: 95,
  },
  {
    name: "Nón bảo hiểm 3/4 Royal M139 kính âm (Vàng bóng)",
    price: 650,
    sale: 450,
    img: "https://i.ibb.co/qgXY86n/2409202405.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 31,
    rating: 4.6,
    sale_count: 150,
  },
  {
    name: "Mũ bảo hiểm fullface Royal M141K vàng bóng",
    price: 960,
    sale: 890,
    img: "https://i.ibb.co/tMJ8VVZ/2409202407.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 7,
    rating: 4.4,
    sale_count: 70,
  },
  {
    name: "Nón bảo hiểm fullface Royal M141 đen mờ",
    price: 890,
    sale: 790,
    img: "https://i.ibb.co/Pch41TC/2409202406.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 11,
    rating: 4.5,
    sale_count: 130,
  },
  {
    name: "Nón bảo hiểm fullface Barock sợi thủy tinh cao cấp B510 (đen bóng)",
    price: 4595,
    sale: 4595,
    img: "https://i.ibb.co/CPvCmX3/2409202408.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 0,
    rating: 4.8,
    sale_count: 240,
  },
  {
    name: "Nón bảo hiểm fullface Barock sợi thủy tinh cao cấp B510 (trắng bóng, decal đỏ xanh)",
    price: 4595,
    sale: 4595,
    img: "https://i.ibb.co/G0Rk464/2409202409.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 0,
    rating: 4.9,
    sale_count: 180,
  },
  {
    name: "Nón bảo hiểm fullface Barock sợi thủy tinh cao cấp B510 (trắng bóng, phối đen đỏ)",
    price: 4595,
    sale: 4595,
    img: "https://i.ibb.co/gjbMYbL/2409202410.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 0,
    rating: 4.7,
    sale_count: 190,
  },
  {
    name: "Nón bảo hiểm nửa đầu Andes màu đen",
    price: 150,
    sale: 100,
    img: "https://i.ibb.co/SnDzwfG/2409202411.jpg",
    stock: 15,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 33,
    rating: 3.9,
    sale_count: 60,
  },
  {
    name: "Nón bảo hiểm nửa đầu Andes màu trắng",
    price: 150,
    sale: 100,
    img: "https://i.ibb.co/JjtZwP5/2409202412.jpg",
    stock: 15,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 33,
    rating: 4.1,
    sale_count: 55,
  },
  {
    name: "Nón bảo hiểm xe đạp trẻ em Royal Kid",
    price: 200,
    sale: 180,
    img: "https://i.ibb.co/HB8rYZw/2409202413.jpg",
    stock: 20,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 10,
    rating: 4.3,
    sale_count: 45,
  },
  {
    name: "Nón bảo hiểm xe đạp Royal Kid kèm đèn LED",
    price: 250,
    sale: 225,
    img: "https://i.ibb.co/JzDwVLL/2409202414.jpg",
    stock: 20,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 10,
    rating: 4.6,
    sale_count: 40,
  },
  {
    name: "Nón bảo hiểm Royal M20 đen mờ",
    price: 550,
    sale: 500,
    img: "https://i.ibb.co/8DqLHTs/2409202415.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 9,
    rating: 4.4,
    sale_count: 80,
  },
  {
    name: "Nón bảo hiểm Royal M20 vàng đồng",
    price: 550,
    sale: 500,
    img: "https://i.ibb.co/Wc5tvvF/2409202416.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 9,
    rating: 4.2,
    sale_count: 70,
  },
  {
    name: "Nón bảo hiểm fullface Yohe 978 đen bóng",
    price: 1290,
    sale: 1150,
    img: "https://i.ibb.co/8rfrVV9/2409202417.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 11,
    rating: 4.7,
    sale_count: 100,
  },
  {
    name: "Nón bảo hiểm fullface Yohe 978 xanh ngọc",
    price: 1290,
    sale: 1150,
    img: "https://i.ibb.co/ZmFNTG6/2409202418.jpg",
    stock: 10,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 11,
    rating: 4.5,
    sale_count: 90,
  },
  {
    name: "Nón bảo hiểm fullface AGV K1 Rossi",
    price: 6990,
    sale: 6590,
    img: "https://i.ibb.co/R4m7R8R/2409202419.jpg",
    stock: 5,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 6,
    rating: 4.9,
    sale_count: 200,
  },
  {
    name: "Nón bảo hiểm fullface AGV K1 đen mờ",
    price: 6990,
    sale: 6590,
    img: "https://i.ibb.co/hfkf5bg/2409202420.jpg",
    stock: 5,
    dspt: "Lấy cảm hứng từ những thiết kế cổ điển,  nón bảo hiểm 3/4 kính âm NOLAN N21 VISOR CLASSIC được cải tiến với phần kính che với thiết kế dài hơn, mang lại sự năng động và trẻ trung.\nVới mục đích hướng tới cho cả di chuyển trong thành phố hay ngoại ô, N21 được trang bị tấm kính che nắng có thể thu vào trong một cách thông minh. Đệm lót với độ mềm và thoáng khi mang lại cảm giác thoải mái cao khi di chuyển.\nVỏ nón bảo hiểm 3/4 kính âm Nolan N21 được làm từ nhựa ABS nguyên sinh\nCó độ bền cao và chịu va đập tốt.\nMút xốp bằng EPS hấp thụ chấn động khi có sự cố.\nQuai mũ dệt 2 lớp bằng sợi tổng hợp, chịu lực giật kéo tốt.",
    discount: 6,
    rating: 4.8,
    sale_count: 195,
  },
];
